workflows:
  ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp/iosApp"
    scripts:
      - name: Cocoapods installation
        script: | 
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR/iosApp
          LATEST_BUILD_NUMBER=0
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
            --sdk iphonesimulator
            --configuration Debug
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false