workflows:
  ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
        XCODE_CONFIGURATION: "Configuration/Config.xcconfig"
      xcode: latest
      cocoapods: default
      java: 21
    scripts:
      - name: Cocoapods Initialization
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod init
      - name: Cocoapods installation
        script: | 
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build ipa for debug mode
        script: | 
          cd $CM_BUILD_DIR/iosApp
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.5' \
          -derivedDataPath Build/ \
          -enableCodeCoverage YES \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false