workflows:
  ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Cocoapods Initialization
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod init
      - name: Cocoapods installation
        script: | 
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for debug mode
        script: | 
          cd $CM_BUILD_DIR/iosApp
          xcodebuild -sdk iphonesimulator -configuration Debug
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false